### ISSUE TITLE
[Queue a Build] Provide option to config triggered build's source branch

### ISSUE THREAD

**Issue by duyhung13** [geeklearningio/gl-vsts-tasks-inception#10]
My special case is:
- MY FIRST build get source code from "refs/heads/master" branch
- I want to trigger MY SECOND build with "refs/heads/automation" branch

I tried to update BUILD_SOURCEBRANCH variables before run this build but it didn't affect.

So I think it would be great enhancement if we could provide source branch option instead of re-used current build source branch.

**Comment by sandorfr** [comment]
I'm curious about the use case behind that need. When I originally wrote this task I wondered if that option could be useful and I couldn't figure a usecase.

This is quite easy to add the option so it's already on the way. That said, there won't be any fancy things like dropdown since they require way more work (as usual PR Welcome).

**Comment by duyhung13** [comment]
@sandorfr wow, thanks for your quickly helping. I'm expecting this feature

**Comment by sandorfr** [comment]
@duyhung13 you're welcome. This should be available now, I leave the testing up to you :)

**Comment by duyhung13** [comment]
@sandorfr It works now :)
Thanks flash man.
