### ISSUE TITLE
build not running on certain build agents

### ISSUE THREAD

**Issue by jprause1234** [geeklearningio/gl-vsts-tasks-inception#14]
Hi.

We have build agents running on a build machine and some on developer machines. After adding this build step and activating it, the build shows that only the agents on the developer machines are possible build agents and the ones on the build machine not. If I disable this build step, everythings builds like before. Any idea to this behavior?
Thanks for your answer!

Cheers
Jan

**Comment by asiffermann** [comment]
Hi @jprause1234 and thank you for your issue! 😃

It may be because of the build agent version number (our task needs 1.91.0 as minimum agent version) or because of the capabilities of your build agents not matching the "demands" registered in the [task.json](https://github.com/geeklearningio/gl-vsts-tasks-inception/blob/master/Tasks/QueueBuild/task.json#L18) (in our case, "npm" is the only requirement).

If so, you can register the capabilities of your build agent from VSTS agent queues settings, or using environment variables on your build agent, as described in [Donovan Brown's blog post](http://donovanbrown.com/post/how-to-register-capabilities-on-your-build-and-release-management-agents).

Please let us know if those explanation could help you fix your issue! 😃

**Comment by jprause1234** [comment]
Hi,

the agent version is the same on every agent machine, but the missing npm was the problem.
Thank you!
Do you know how to find out which prerequisites are missing for a build on an agent for a specific build?

Cheers,
Jan.

**Comment by asiffermann** [comment]
Hi,

Great to know it solved your issue 😃
I do not know if it is possible to see these informations easily OOTB, but I think it would be a great idea for an extension!

**Comment by sandorfr** [comment]
Just a random thought but I wonder if we could remove this demand as node is supposed to be bundled with the agent @asiffermann ?

**Comment by asiffermann** [comment]
Oh you're right, I don't even know why we have this demand for this task, in fact!
